// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200309095159");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec", 3300);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.min", 1);
user_pref("app.normandy.user_id", "617eed9e-613f-4422-85c3-0d1c304a370c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1586266673);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1586266648);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1586267465);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1586270948);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1586266703);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3088);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1586266643);
user_pref("browser.laterrun.bookkeeping.sessionCount", 9);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2c76e014-1a39-4580-b754-fad6041be97d}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1586274736534");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1586276562534");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1586274736946");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1586278336946");
user_pref("browser.search.region", "IE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200309095159");
user_pref("browser.slowStartup.averageTime", 1164);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200309095159");
user_pref("browser.startup.homepage_override.mstone", "74.0");
user_pref("browser.startup.lastColdStartupCheck", 1586274756);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.placeholderName.private", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1586266646636");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "74.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "423b8cf011a54a0a8f5bae8aef70c133");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200309095159");
user_pref("extensions.lastAppVersion", "74.0");
user_pref("extensions.lastPlatformVersion", "74.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b091e42d-8250-4bfd-bc7d-28394ccebe62\",\"formautofill@mozilla.org\":\"48871184-861e-4202-8346-33526317f905\",\"screenshots@mozilla.org\":\"05a22ab0-b1fc-4db4-a7dd-4d5916751845\",\"webcompat-reporter@mozilla.org\":\"3c20be51-724a-4704-8675-7f6a5e1b0941\",\"webcompat@mozilla.org\":\"ba9da463-0046-47fc-a717-b24498945913\",\"default-theme@mozilla.org\":\"f1a2b01e-221e-42f5-8c7a-fbb6ef5a6a14\",\"google@search.mozilla.org\":\"e39447e1-6d7d-4a9d-b10b-d4b4fdc262f4\",\"amazondotcom@search.mozilla.org\":\"db006544-cc6a-4d7b-be7d-025430058112\",\"bing@search.mozilla.org\":\"96439fd7-74cb-4131-a774-da74a19f292e\",\"ddg@search.mozilla.org\":\"a1b528ce-7dbd-496b-b1d9-81d2d9be4471\",\"ebay@search.mozilla.org\":\"542434a0-29e1-417f-8fca-5b8efb07e134\",\"twitter@search.mozilla.org\":\"aeb8a478-bf47-4f29-bc2e-548742c3c383\",\"wikipedia@search.mozilla.org\":\"fdd6ba40-b04a-431c-a78c-d4a38b6593b7\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1586270950);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200309095159");
user_pref("media.gmp-manager.lastCheck", 1586270949);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d25230ae-3313-4d72-a56b-91b11718c57c");
user_pref("security.sandbox.plugin.tempDirSuffix", "7aa72d62-62bc-4037-835e-c54e926ea7cf");
user_pref("services.blocklist.addons.checked", 1586274736);
user_pref("services.blocklist.gfx.checked", 1586274736);
user_pref("services.blocklist.pinning.checked", 1586271004);
user_pref("services.blocklist.plugins.checked", 1586274736);
user_pref("services.settings.clock_skew_seconds", -1);
user_pref("services.settings.last_etag", "\"1586272725414\"");
user_pref("services.settings.last_update_seconds", 1586274736);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1586274736);
user_pref("services.settings.main.cfr-fxa.last_check", 1586274736);
user_pref("services.settings.main.cfr.last_check", 1586274736);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1586274736);
user_pref("services.settings.main.hijack-blocklists.last_check", 1586274736);
user_pref("services.settings.main.language-dictionaries.last_check", 1586274736);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1586274736);
user_pref("services.settings.main.public-suffix-list.last_check", 1586274736);
user_pref("services.settings.main.sites-classification.last_check", 1586274736);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1586274736);
user_pref("services.settings.main.whats-new-panel.last_check", 1586274736);
user_pref("services.settings.security.onecrl.checked", 1586270953);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1586274755);
user_pref("toolkit.telemetry.cachedClientID", "0d70dabc-cdd5-4ad9-af86-5b1557b5bc20");
user_pref("toolkit.telemetry.previousBuildID", "20200309095159");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
